### ISSUE TITLE
Second player gets blocked unnessarily

### ISSUE THREAD

**Issue by Lharp5** [Elephly/MagicRealm#10]
Amazon moved from inn to borderlands 1(where a monster was located)
Dwarf moved to bad valley 2.
Dwarf successfully moves
- says dwarf is blocked

Amazon moves
- blocked by monster(correctly)

**Comment by Lharp5** [comment]
Client was locked up after the fact.

**Comment by ColinZeidler** [comment]
have not encountered this in lots of testing
